//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_LogoIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int fid { get; set; }
        public string femail { get; set; }
        public string fpassword { get; set; }
        public string fusername { get; set; }
        public string fgender { get; set; }
        public string faddress { get; set; }
        public string fphone { get; set; }
        public string fphoto { get; set; }
    }
}
